// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTxBUNdN-fceiOCf2x3Rso9Xks_ZZpYdo',
    appId: '1:559685416830:web:8793b28ff02a9ade14e52f',
    messagingSenderId: '559685416830',
    projectId: 'chatapp-flutter-2023',
    authDomain: 'chatapp-flutter-2023.firebaseapp.com',
    storageBucket: 'chatapp-flutter-2023.appspot.com',
    measurementId: 'G-FS5NG3420Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIlhGJBUMtYCqQ6lZVm5teZMjeizPQnw8',
    appId: '1:559685416830:android:a8f1e5640bcc639f14e52f',
    messagingSenderId: '559685416830',
    projectId: 'chatapp-flutter-2023',
    storageBucket: 'chatapp-flutter-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ZeqpKrV5mZbxqAGw5SU01lfmm5BwiUY',
    appId: '1:559685416830:ios:2ab4e528019a83de14e52f',
    messagingSenderId: '559685416830',
    projectId: 'chatapp-flutter-2023',
    storageBucket: 'chatapp-flutter-2023.appspot.com',
    iosClientId: '559685416830-ocpq3q7c8i5bkm9b05a2hu2ku2cf802r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ZeqpKrV5mZbxqAGw5SU01lfmm5BwiUY',
    appId: '1:559685416830:ios:2ab4e528019a83de14e52f',
    messagingSenderId: '559685416830',
    projectId: 'chatapp-flutter-2023',
    storageBucket: 'chatapp-flutter-2023.appspot.com',
    iosClientId: '559685416830-ocpq3q7c8i5bkm9b05a2hu2ku2cf802r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
