// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybpXbm-uYfdyCAOnJGVcD2KJN7QwmNMc',
    appId: '1:455312819059:web:084b258327f3c6d1f47b06',
    messagingSenderId: '455312819059',
    projectId: 'booking-car-2023',
    authDomain: 'booking-car-2023.firebaseapp.com',
    storageBucket: 'booking-car-2023.appspot.com',
    measurementId: 'G-MHBJ5MDWY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWLi_NfVzWi3KukMvkJUZt3EPpMDabwVs',
    appId: '1:455312819059:android:a4bad92d2335d90df47b06',
    messagingSenderId: '455312819059',
    projectId: 'booking-car-2023',
    storageBucket: 'booking-car-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ljCafYNDE07CqBtK46zz-hwYgPigCFw',
    appId: '1:455312819059:ios:985b53a9d625d483f47b06',
    messagingSenderId: '455312819059',
    projectId: 'booking-car-2023',
    storageBucket: 'booking-car-2023.appspot.com',
    iosClientId: '455312819059-q0aiodmjb88h45pad9sgrce7h6nnqkcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ljCafYNDE07CqBtK46zz-hwYgPigCFw',
    appId: '1:455312819059:ios:985b53a9d625d483f47b06',
    messagingSenderId: '455312819059',
    projectId: 'booking-car-2023',
    storageBucket: 'booking-car-2023.appspot.com',
    iosClientId: '455312819059-q0aiodmjb88h45pad9sgrce7h6nnqkcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingCar',
  );
}
